"""Curated glossary expansion — IT and everyday/support/mail volume.

The 124-concept core covered the manufacturing shop floor completely but left IT
and everyday language thin (measured coverage 26 % and 38 % against a broader
vocabulary, versus 48 % for manufacturing — `evals/glossary_error_rate.py`). This
module adds volume where it is missing and deliberately adds none to
manufacturing, which is already complete for the terms that matter.

Same authoring rules as the core (`scripts/curated_glossary_data.py`):
  * one term -> exactly ONE concept across ALL domains. The index is flat, so a
    word appearing twice is an ambiguous mapping. `merge_sources` refuses it and
    the build stops; this is checked, not assumed.
  * no proper names, brands, vendors, places (principle 17)
  * ASCII and umlaut spellings both listed where the ASCII form is common in
    typed tickets
  * terms that occur in support / process / mail / IT messages, not dictionary
    completeness
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# IT — infrastructure, software engineering, security, operations
# ---------------------------------------------------------------------------

IT2: dict[str, dict[str, list[str]]] = {
    # -- hardware ----------------------------------------------------------
    "monitor": {"de": ["bildschirm", "monitor", "anzeige"],
                "en": ["monitor", "screen", "display"]},
    "keyboard": {"de": ["tastatur"],
                 "en": ["keyboard"]},
    "mouse": {"de": ["maus", "zeigegeraet"],
              "en": ["mouse", "pointing device"]},
    "printer": {"de": ["drucker", "druckgeraet"],
                "en": ["printer"]},
    "scanner": {"de": ["scanner"],
                "en": ["scanner"]},
    "laptop": {"de": ["laptop", "notebook", "rechner mobil"],
               "en": ["laptop", "notebook"]},
    "desktop_pc": {"de": ["desktoprechner", "standrechner"],
                   "en": ["desktop computer", "desktop pc"]},
    "tablet": {"de": ["tablet"],
               "en": ["tablet"]},
    "smartphone": {"de": ["smartphone", "diensthandy", "mobiltelefon"],
                   "en": ["smartphone", "mobile phone"]},
    "router": {"de": ["router"],
               "en": ["router"]},
    "netzwerkverteiler": {"de": ["netzwerkverteiler", "switcheinheit"],
                          "en": ["network switch", "ethernet switch"]},
    "modem": {"de": ["modem"],
              "en": ["modem"]},
    "mainboard": {"de": ["hauptplatine", "mainboard"],
                  "en": ["motherboard", "mainboard"]},
    "grafikkarte": {"de": ["grafikkarte"],
                    "en": ["graphics card", "gpu"]},
    "festplatte": {"de": ["festplatte", "hdd", "laufwerk"],
                   "en": ["hard drive", "hdd", "drive"]},
    "ssd": {"de": ["ssd", "halbleiterlaufwerk"],
            "en": ["ssd", "solid state drive"]},
    "usb": {"de": ["usb", "usbanschluss"],
            "en": ["usb", "usb port"]},
    "anschluss": {"de": ["anschluss", "schnittstellenport"],
                  "en": ["port", "socket"]},
    "adapter": {"de": ["adapter", "zwischenstecker"],
                "en": ["adapter", "dongle"]},
    "dockingstation": {"de": ["dockingstation", "docking"],
                       "en": ["docking station", "dock"]},
    "akku": {"de": ["akku", "batterie", "stromversorgung"],
             "en": ["battery", "accumulator"]},
    "netzteil": {"de": ["netzteil", "ladegeraet"],
                 "en": ["power supply", "charger"]},
    "headset": {"de": ["headset", "kopfhoerer"],
                "en": ["headset", "headphones"]},
    "webcam": {"de": ["webcam", "kamera"],
               "en": ["webcam", "camera"]},
    "beamer": {"de": ["beamer", "projektor"],
               "en": ["projector", "beamer"]},

    # -- software engineering ---------------------------------------------
    "operating_system": {"de": ["betriebssystem"],
                          "en": ["operating system", "os"]},
    "browser": {"de": ["browser", "webbrowser"],
                "en": ["browser", "web browser"]},
    "editor": {"de": ["editor", "texteditor"],
               "en": ["editor", "text editor"]},
    "compiler": {"de": ["compiler", "uebersetzer"],
                 "en": ["compiler"]},
    "debugger": {"de": ["debugger", "fehlersuche"],
                 "en": ["debugger"]},
    "source_code": {"de": ["quellcode", "quelltext"],
                    "en": ["source code", "codebase"]},
    "repository": {"de": ["repository", "quellcodearchiv"],
                   "en": ["repository", "repo"]},
    "branch": {"de": ["zweig", "entwicklungszweig"],
               "en": ["branch"]},
    "commit": {"de": ["committen", "versionsstand einchecken"],
               "en": ["commit", "check-in"]},
    "pull_request": {"de": ["zusammenfuehrungsantrag", "pull request"],
                     "en": ["pull request", "merge request"]},
    "code_review": {"de": ["codereview", "codeueberpruefung"],
                    "en": ["code review", "peer review"]},
    "unit_test": {"de": ["unittest", "modultest"],
                  "en": ["unit test"]},
    "integration_test": {"de": ["integrationstest"],
                          "en": ["integration test"]},
    "test_suite": {"de": ["testsuite", "testumfang"],
                   "en": ["test suite", "test set"]},
    "build": {"de": ["buildvorgang", "uebersetzungsvorgang"],
              "en": ["build"]},
    "pipeline": {"de": ["pipeline", "buildkette"],
                 "en": ["pipeline", "build chain"]},
    "artifact_build": {"de": ["buildartefakt"],
                       "en": ["build artifact"]},
    "dependency": {"de": ["abhaengigkeit", "bibliotheksabhaengigkeit"],
                   "en": ["dependency", "dep"]},
    "library": {"de": ["bibliothek", "lib"],
                "en": ["library", "lib"]},
    "framework": {"de": ["framework", "rahmenwerk"],
                  "en": ["framework"]},
    "package": {"de": ["paket", "softwarepaket"],
                "en": ["package", "bundle"]},
    "version_control": {"de": ["versionsverwaltung"],
                        "en": ["version control", "source control"]},
    "changelog": {"de": ["aenderungsprotokoll", "changelog"],
                  "en": ["changelog", "release notes"]},
    "refactoring": {"de": ["refactoring", "umbau"],
                    "en": ["refactoring"]},
    "api_endpoint": {"de": ["apiendpunkt", "schnittstellenadresse"],
                     "en": ["api endpoint", "endpoint address"]},
    "payload": {"de": ["nutzlast", "datenpaket"],
                "en": ["payload", "body"]},
    "response": {"de": ["antwort", "antwortdaten"],
                  "en": ["response"]},
    "status_code": {"de": ["statuscode", "httpcode"],
                    "en": ["status code", "http status"]},
    "rate_limit": {"de": ["ratenbegrenzung", "aufrufgrenze"],
                   "en": ["rate limit", "throttling"]},
    "webhook": {"de": ["webhook", "rueckruf"],
                "en": ["webhook", "callback"]},
    "cronjob": {"de": ["zeitgesteuerter auftrag", "cronjob"],
                "en": ["cron job", "scheduled task"]},
    "daemon": {"de": ["hintergrunddienst"],
               "en": ["daemon", "background service"]},

    # -- data --------------------------------------------------------------
    "table": {"de": ["tabelle", "datentabelle"],
              "en": ["table", "data table"]},
    "column": {"de": ["spalte", "feld"],
               "en": ["column", "field"]},
    "row": {"de": ["zeile", "datensatz"],
            "en": ["row", "table row"]},
    "schema": {"de": ["schema", "datenstruktur"],
               "en": ["schema", "data structure"]},
    "index": {"de": ["index", "suchindex"],
              "en": ["index"]},
    "primary_key": {"de": ["primaerschluessel"],
                    "en": ["primary key"]},
    "foreign_key": {"de": ["fremdschluessel"],
                    "en": ["foreign key"]},
    "join": {"de": ["verknuepfung", "tabellenverknuepfung"],
             "en": ["join", "table join"]},
    "view": {"de": ["sicht", "datenbanksicht"],
             "en": ["view", "db view"]},
    "migration": {"de": ["migration", "datenmigration"],
                  "en": ["migration"]},
    "replication": {"de": ["replikation", "spiegelung"],
                    "en": ["replication", "mirroring"]},
    "cache": {"de": ["zwischenspeicher", "cache"],
              "en": ["cache", "buffer"]},
    "session": {"de": ["sitzung", "sessionszustand"],
                "en": ["session"]},
    "cookie": {"de": ["cookie", "kennung"],
               "en": ["cookie"]},
    "token": {"de": ["token", "zugangstoken"],
              "en": ["token", "auth token"]},
    "export": {"de": ["export", "datenausgabe"],
               "en": ["export", "extract"]},
    "import": {"de": ["import", "einlesen"],
               "en": ["import", "ingest"]},
    "batch_job": {"de": ["stapelverarbeitung", "batchlauf"],
                  "en": ["batch job", "batch process"]},
    "data_loss": {"de": ["datenverlust"],
                  "en": ["data loss"]},
    "data_quality": {"de": ["datenqualitaet"],
                     "en": ["data quality"]},

    # -- security ----------------------------------------------------------
    "vulnerability": {"de": ["schwachstelle", "sicherheitsluecke"],
                      "en": ["vulnerability", "security flaw"]},
    "exploit": {"de": ["ausnutzung", "schwachstellenausnutzung"],
                "en": ["exploit", "attack vector"]},
    "phishing": {"de": ["phishing", "betrugsmail"],
                 "en": ["phishing", "spam mail"]},
    "ransomware": {"de": ["erpressersoftware", "ransomware"],
                   "en": ["ransomware", "extortion software"]},
    "spyware": {"de": ["spaehsoftware", "spyware"],
                "en": ["spyware", "tracking software"]},
    "denial_of_service": {"de": ["dienstblockade", "ueberlastangriff"],
                          "en": ["denial of service", "dos attack"]},
    "penetration_test": {"de": ["penetrationstest", "sicherheitstest"],
                         "en": ["penetration test", "pentest"]},
    "two_factor": {"de": ["zweifaktoranmeldung", "zwei faktor"],
                   "en": ["two-factor authentication", "2fa"]},
    "single_sign_on": {"de": ["einmalanmeldung", "zentrale anmeldung"],
                       "en": ["single sign-on", "sso"]},
    "identity": {"de": ["identitaet", "benutzeridentitaet"],
                 "en": ["identity", "user identity"]},
    "privilege_escalation": {"de": ["rechteausweitung", "privilegienausweitung"],
                             "en": ["privilege escalation"]},
    "audit_log": {"de": ["auditprotokoll", "revisionsprotokoll"],
                  "en": ["audit log", "audit trail"]},
    "datenschutz": {"de": ["datenschutz", "datenrichtlinie"],
                    "en": ["data protection", "privacy"]},
    "pseudonymisierung": {"de": ["pseudonymisierung", "anonymisierung"],
                          "en": ["pseudonymisation", "anonymisation"]},
    "loeschung": {"de": ["loeschung", "datenloeschung"],
                  "en": ["deletion", "erasure"]},
    "einwilligung": {"de": ["einwilligung", "zustimmung"],
                     "en": ["consent", "approval to process"]},

    # -- operations --------------------------------------------------------
    "container": {"de": ["container", "laufzeitumgebung"],
                  "en": ["container"]},
    "image_ops": {"de": ["abbild", "containerdatentraeger"],
                  "en": ["image", "container image"]},
    "cluster": {"de": ["cluster", "verbund"],
                "en": ["cluster"]},
    "node": {"de": ["knoten", "serverknoten"],
             "en": ["node", "worker node"]},
    "load_balancer": {"de": ["lastverteiler"],
                      "en": ["load balancer"]},
    "proxy": {"de": ["proxy", "vermittlungsrechner"],
              "en": ["proxy", "forward proxy"]},
    "gateway": {"de": ["gateway", "netzuebergang"],
                "en": ["gateway"]},
    "subnet": {"de": ["subnetz"],
               "en": ["subnet"]},
    "ip_address": {"de": ["ipadresse"],
                   "en": ["ip address"]},
    "dns": {"de": ["namensaufloesung", "dns"],
            "en": ["dns", "name resolution"]},
    "bandwidth": {"de": ["bandbreite", "durchsatzrate"],
                  "en": ["bandwidth"]},
    "uptime": {"de": ["verfuegbarkeit", "betriebszeit"],
               "en": ["uptime", "availability"]},
    "service_level": {"de": ["servicelevel", "vereinbarungsniveau"],
                      "en": ["service level agreement", "sla"]},
    "postmortem": {"de": ["nachbereitung", "stoerungsnachbereitung"],
                   "en": ["postmortem", "incident review"]},
    "root_cause": {"de": ["ursachenanalyse", "grundursache"],
                   "en": ["root cause", "root cause analysis"]},
    "escalation": {"de": ["eskalation", "hochstufung"],
                   "en": ["escalation"]},
    "on_call": {"de": ["rufbereitschaft", "bereitschaftsdienst"],
                "en": ["on-call", "standby duty"]},
    "runbook": {"de": ["ablaufanweisung", "runbook"],
                "en": ["runbook", "playbook"]},
    "alert": {"de": ["warnmeldung", "alarmierung"],
              "en": ["alert", "notification"]},
    "threshold": {"de": ["schwellwert", "grenzwert"],
                  "en": ["threshold", "limit value"]},
    "dashboard": {"de": ["uebersichtsseite", "dashboard"],
                  "en": ["dashboard", "overview page"]},
    "metric": {"de": ["kennzahl", "metrik"],
               "en": ["metric", "measure"]},
    "trend": {"de": ["verlauf", "entwicklung"],
              "en": ["trend", "progression"]},

    # -- delivery process --------------------------------------------------
    "sprint": {"de": ["sprint", "arbeitszyklus"],
               "en": ["sprint", "iteration"]},
    "backlog": {"de": ["rueckstand", "aufgabenliste"],
                "en": ["backlog", "task list"]},
    "epic": {"de": ["epos", "grossvorhaben"],
             "en": ["epic", "large story"]},
    "user_story": {"de": ["anwenderstory", "nutzergeschichte"],
                   "en": ["user story"]},
    "estimation": {"de": ["aufwandsschaetzung", "schaetzung"],
                   "en": ["estimation", "effort estimate"]},
    "standup": {"de": ["taegliche abstimmung", "standup"],
                "en": ["standup", "daily meeting"]},
    "retrospective": {"de": ["retrospektive", "rueckblick"],
                      "en": ["retrospective", "retro"]},
    "roadmap": {"de": ["fahrplan", "roadmap"],
                "en": ["roadmap", "plan of record"]},
    "milestone": {"de": ["meilenstein"],
                  "en": ["milestone"]},
    "specification": {"de": ["spezifikation", "leistungsbeschreibung"],
                      "en": ["specification", "spec"]},
    "acceptance_criteria": {"de": ["abnahmekriterium", "abnahmekriterien"],
                            "en": ["acceptance criteria"]},
    "definition_of_done": {"de": ["fertigstellungskriterium"],
                           "en": ["definition of done"]},

    # -- workplace IT / helpdesk -------------------------------------------
    "helpdesk": {"de": ["servicestelle", "hilfestelle"],
                 "en": ["helpdesk", "service desk"]},
    "ticket_queue": {"de": ["vorgangswarteschlange", "ticketliste"],
                     "en": ["ticket queue", "queue"]},
    "asset": {"de": ["anlagegut", "inventarobjekt"],
              "en": ["asset", "device record"]},
    "lizenz": {"de": ["lizenz", "nutzungsrecht"],
               "en": ["software license", "licence key"]},
    "provisioning": {"de": ["bereitstellungvonressourcen", "ausstattung"],
                     "en": ["provisioning", "setup"]},
    "decommission": {"de": ["ausserbetriebnahme", "stilllegung"],
                     "en": ["decommissioning", "retirement"]},
    "remote_access": {"de": ["fernzugriff", "fernwartung"],
                      "en": ["remote access", "remote session"]},
    "vpn": {"de": ["vpn", "verschluesselter tunnel"],
            "en": ["vpn", "virtual private network"]},
    "fileshare": {"de": ["dateifreigabe", "netzlaufwerk"],
                  "en": ["file share", "network drive"]},
    "group_policy": {"de": ["gruppenrichtlinie"],
                     "en": ["group policy"]},
    "mailbox": {"de": ["postfach", "briefkasten"],
                "en": ["mailbox", "inbox"]},
    "distribution_list": {"de": ["verteiler", "verteilerliste"],
                          "en": ["distribution list", "mailing list"]},
    "calendar_invite": {"de": ["terminanfrage", "termineinladung"],
                        "en": ["calendar invite", "meeting request"]},
    "out_of_office": {"de": ["abwesenheitsnotiz", "abwesenheit"],
                      "en": ["out of office", "absence note"]},
    "software_inventory": {"de": ["softwarebestand", "softwareverzeichnis"],
                           "en": ["software inventory", "installed software"]},
    "install": {"de": ["installation", "einrichten"],
                "en": ["install", "installation"]},
    "uninstall": {"de": ["deinstallation", "entfernen"],
                  "en": ["uninstall", "remove"]},
    "lizenzablauf": {"de": ["lizenzablauf", "lizenzlaufzeit"],
                     "en": ["license expiry", "license term"]},
}

# ---------------------------------------------------------------------------
# EVERYDAY / OFFICE / SUPPORT / MAIL
# ---------------------------------------------------------------------------

EVERYDAY2: dict[str, dict[str, list[str]]] = {
    # -- mail / correspondence --------------------------------------------
    "email": {"de": ["e-mail", "email", "mail"],
              "en": ["email", "e-mail"]},
    "sender": {"de": ["absender", "sender"],
               "en": ["sender", "from"]},
    "recipient": {"de": ["empfaenger", "adressat"],
                  "en": ["recipient", "addressee"]},
    "subject_line": {"de": ["betreff", "betreffzeile"],
                     "en": ["subject", "subject line"]},
    "attachment": {"de": ["anhang", "dateianhang"],
                   "en": ["attachment", "enclosure"]},
    "cc": {"de": ["inkopie", "kopieempfaenger"],
           "en": ["cc", "carbon copy"]},
    "reply": {"de": ["antwortmail", "erwiderung"],
              "en": ["reply", "response mail"]},
    "forward": {"de": ["weiterleitung", "weiterleiten"],
                "en": ["forward", "redirect"]},
    "draft": {"de": ["entwurf"],
              "en": ["draft"]},
    "signature": {"de": ["signatur", "fusszeile"],
                  "en": ["signature", "sign-off"]},
    "bounce": {"de": ["unzustellbar", "zurueckgewiesen"],
               "en": ["bounce", "undeliverable"]},
    "spam_filter": {"de": ["spamfilter", "werbefilter"],
                    "en": ["spam filter", "junk filter"]},
    "mailbox_full": {"de": ["postfach voll", "speichergrenze"],
                     "en": ["mailbox full", "quota exceeded"]},
    "letter": {"de": ["brief", "schreiben"],
               "en": ["letter", "written notice"]},
    "memo": {"de": ["vermerk", "notiz"],
             "en": ["memo", "note"]},
    "circular": {"de": ["rundschreiben", "umlauf"],
                 "en": ["circular", "broadcast message"]},
    "salutation": {"de": ["anrede"],
                   "en": ["salutation", "greeting"]},
    "closing": {"de": ["grussformel", "schlussformel"],
                "en": ["closing", "valediction"]},
    "reminder_mail": {"de": ["erinnerungsmail", "mahnung"],
                      "en": ["reminder mail", "dunning mail"]},

    # -- requests / processing --------------------------------------------
    "instruction": {"de": ["anweisung", "vorgabe"],
                    "en": ["instruction", "directive"]},
    "guideline": {"de": ["richtlinie", "leitfaden"],
                  "en": ["guideline", "policy"]},
    "procedure_step": {"de": ["arbeitsschritt", "verfahrensschritt"],
                       "en": ["process step", "procedure step"]},
    "handover": {"de": ["uebergabe", "uebergabeprotokoll"],
                 "en": ["handover", "transfer of work"]},
    "approval_chain": {"de": ["genehmigungskette", "freigabeweg"],
                       "en": ["approval chain", "sign-off path"]},
    "rejection": {"de": ["ablehnung", "absage"],
                  "en": ["rejection", "denial"]},
    "withdrawal": {"de": ["ruecknahme", "widerruf"],
                   "en": ["withdrawal", "revocation"]},
    "reminder": {"de": ["wiedervorlage", "erinnerung"],
                 "en": ["reminder", "prompt"]},
    "deadline_extension": {"de": ["fristverlaengerung", "aufschub"],
                           "en": ["deadline extension", "extension"]},
    "priority_change": {"de": ["prioritaetsaenderung", "umstufung"],
                        "en": ["priority change", "reprioritisation"]},
    "status_update": {"de": ["statusmeldung", "zwischenstand"],
                      "en": ["status update", "progress report"]},
    "follow_up": {"de": ["nachfassen", "nachverfolgung"],
                  "en": ["follow up", "chase"]},
    "escalate_request": {"de": ["hochstufen", "zum vorgesetzten"],
                         "en": ["escalate", "raise to manager"]},

    # -- time and absence --------------------------------------------------
    "working_hours": {"de": ["arbeitszeit", "arbeitsstunden"],
                      "en": ["working hours", "hours"]},
    "core_hours": {"de": ["kernzeit", "kernarbeitszeit"],
                   "en": ["core hours", "core time"]},
    "flexitime": {"de": ["gleitzeit", "gleitzeitkonto"],
                  "en": ["flexitime", "flexible hours"]},
    "time_off_request": {"de": ["urlaubsantrag", "abwesenheitsantrag"],
                         "en": ["time off request", "leave request"]},
    "parental_leave": {"de": ["elternzeit", "erziehungsurlaub"],
                       "en": ["parental leave", "family leave"]},
    "public_holiday": {"de": ["feiertag", "gesetzlicher feiertag"],
                       "en": ["public holiday", "bank holiday"]},
    "shift_swap": {"de": ["schichttausch", "diensttausch"],
                   "en": ["shift swap", "shift exchange"]},
    "timesheet": {"de": ["stundenzettel", "arbeitszeitnachweis"],
                  "en": ["timesheet", "time record"]},
    "absence_report": {"de": ["abwesenheitsmeldung", "fehlzeit"],
                       "en": ["absence report", "absence record"]},

    # -- money and documents -----------------------------------------------
    "cost_centre": {"de": ["kostenstelle", "kostenstelle zuordnung"],
                    "en": ["cost centre", "cost center"]},
    "purchase_request": {"de": ["bestellanforderung", "bedarfsmeldung"],
                         "en": ["purchase request", "requisition"]},
    "quotation": {"de": ["angebot", "kostenvoranschlag"],
                  "en": ["quotation", "estimate"]},
    "credit_note": {"de": ["gutschriftsbeleg", "stornorechnung"],
                    "en": ["credit memo", "credit voucher"]},
    "remittance": {"de": ["zahlungsavis", "ueberweisungsbeleg"],
                   "en": ["remittance", "payment advice"]},
    "dunning": {"de": ["mahnwesen", "zahlungserinnerung"],
                "en": ["dunning", "payment reminder"]},
    "currency": {"de": ["waehrung", "fremdwaehrung"],
                 "en": ["currency", "foreign currency"]},
    "tax": {"de": ["steuer", "umsatzsteuer"],
            "en": ["tax", "vat"]},
    "discount": {"de": ["rabatt", "nachlass"],
                 "en": ["discount", "rebate"]},
    "contract_term": {"de": ["vertragslaufzeit", "laufzeit"],
                      "en": ["contract term", "term"]},
    "amendment_doc": {"de": ["nachtragsvereinbarung", "vertragsanpassung"],
                      "en": ["amendment", "contract addendum"]},
    "purchase_order": {"de": ["bestellnummer", "auftragsbestaetigung"],
                       "en": ["po", "order confirmation"]},
    "delivery_note": {"de": ["lieferschein", "warenbegleitschein"],
                      "en": ["delivery note", "packing slip"]},
    "archiving": {"de": ["archivierung", "ablage"],
                  "en": ["archiving", "filing"]},
    "retention": {"de": ["aufbewahrungsfrist", "aufbewahrung"],
                  "en": ["retention", "retention period"]},
    "record": {"de": ["akte", "unterlage"],
               "en": ["file", "record"]},
    "form": {"de": ["formular", "vordruck"],
             "en": ["form", "template"]},
    "signature_legal": {"de": ["unterschrift", "zeichnung"],
                        "en": ["signing", "legal signature"]},
    "power_of_attorney": {"de": ["vollmacht", "vertretungsvollmacht"],
                          "en": ["power of attorney", "authorisation"]},

    # -- people and organisation -------------------------------------------
    "colleague": {"de": ["kollege", "kollegin"],
                  "en": ["colleague", "coworker"]},
    "team_lead": {"de": ["teamleitung", "gruppenleiter"],
                  "en": ["team lead", "team leader"]},
    "new_hire": {"de": ["neueinstellung", "neuer mitarbeiter"],
                 "en": ["new hire", "newcomer"]},
    "departure": {"de": ["austritt", "personalabgang"],
                  "en": ["departure", "offboarding"]},
    "role": {"de": ["rolle", "funktion"],
             "en": ["role", "function"]},
    "responsibility": {"de": ["verantwortlichkeit", "zustaendigkeit"],
                       "en": ["responsibility", "ownership"]},
    "delegation": {"de": ["delegation", "uebertragung"],
                   "en": ["delegation", "assignment"]},
    "team_meeting": {"de": ["teambesprechung", "abstimmungsrunde"],
                     "en": ["team meeting", "team call"]},
    "one_on_one": {"de": ["einzelgespraech", "vier augen gespraech"],
                   "en": ["one-on-one", "individual meeting"]},
    "feedback": {"de": ["rueckmeldung", "feedback"],
                 "en": ["feedback", "review comment"]},
    "appraisal": {"de": ["beurteilung", "mitarbeitergespraech"],
                  "en": ["appraisal", "performance review"]},
    "goal": {"de": ["ziel", "zielsetzung"],
             "en": ["goal", "objective"]},
    "qualification": {"de": ["qualifikation", "befaehigung"],
                      "en": ["qualification", "competence"]},
    "works_agreement": {"de": ["betriebsvereinbarung", "dienstvereinbarung"],
                        "en": ["works agreement", "company agreement"]},
    "escalation_contact": {"de": ["ansprechpartner", "kontaktperson"],
                           "en": ["contact person", "point of contact"]},
    "org_unit": {"de": ["organisationseinheit", "fachbereich"],
                 "en": ["organisational unit", "business unit"]},
    "temporary_staff": {"de": ["leiharbeit", "zeitarbeit"],
                        "en": ["temporary staff", "agency worker"]},

    # -- support interaction -----------------------------------------------
    "inquiry_status": {"de": ["bearbeitungsstand", "bearbeitungsstatus"],
                       "en": ["case status", "processing state"]},
    "resolved": {"de": ["geloest", "erledigt"],
                 "en": ["resolved", "closed"]},
    "reopened": {"de": ["wiedereroeffnet", "erneut geoeffnet"],
                 "en": ["reopened", "reopened case"]},
    "waiting_customer": {"de": ["wartet auf kunde", "rueckfrage offen"],
                         "en": ["waiting for customer", "pending reply"]},
    "waiting_third_party": {"de": ["wartet auf dienstleister", "extern offen"],
                            "en": ["waiting for third party", "waiting on vendor"]},
    "workaround": {"de": ["ueberbrueckung", "behelfsloesung"],
                   "en": ["workaround", "interim fix"]},
    "root_fix": {"de": ["endlosung", "dauerhafte loesung"],
                 "en": ["permanent fix", "definitive solution"]},
    "recurrence": {"de": ["wiederholung", "erneutes auftreten"],
                   "en": ["recurrence", "repeat occurrence"]},
    "impact": {"de": ["auswirkung", "betroffenheit"],
               "en": ["impact", "affected scope"]},
    "affected_users": {"de": ["betroffene nutzer", "betroffenenkreis"],
                       "en": ["affected users", "impacted users"]},
    "severity": {"de": ["schweregrad", "ausmass"],
                 "en": ["severity", "severity level"]},
    "workload": {"de": ["arbeitslast", "auslastung"],
                 "en": ["workload", "load"]},
    "response_time": {"de": ["reaktionszeit", "rueckmeldezeit"],
                      "en": ["reaction time", "first response time"]},
    "resolution_time": {"de": ["loesungszeit", "bearbeitungsdauer"],
                        "en": ["resolution time", "handling time"]},
    "satisfaction": {"de": ["zufriedenheit", "kundenzufriedenheit"],
                     "en": ["satisfaction", "customer satisfaction"]},
}
